Updated list of files in service worker for latest Webviewer version
PDFTron/webviewer-offline-sample pull request #3
Opened 2023-09-27 00:36 UTC by Johnny-kung

2023-10-03 16:36 UTC, mparizeau-pdftron requested changes
Loading PDF doesn't work for me. Looks like it's missing the files in the optimized folder pdf/lean/optimized

2023-10-03 22:07 UTC, Johnny-kung commented
I added a script to generate a json file, which contains the list of the files' path to be cached by service worker.

2023-10-11 19:21 UTC, mparizeau-pdftron requested changes

2023-10-11 19:21 UTC, mparizeau-pdftron commented on prepare-serviceworker-list.js
> +  { name: 'core', path: './public/lib/core/' },
Looks like it doesn't work if I try to content editing. Not sure if we need to explicitly specify `contentEdit`, `officeEditor` and `assets` folders?

2023-10-12 18:09 UTC, Johnny-kung commented
<img width="1144" alt="Screen Shot 2023-10-12 at 11 04 19 AM" src="https://github.com/PDFTron/webviewer-offline-sample/assets/104520223/9b9cc936-defa-4f9a-bab6-0a72513fccb2">
<img width="1138" alt="Screen Shot 2023-10-12 at 11 04 36 AM" src="https://github.com/PDFTron/webviewer-offline-sample/assets/104520223/47b06094-759b-474e-b0b7-0d1341bf0e72">

Content edit seems not able to edit the first page in the sample pdf file, either with the server running or in offline. This is probably not related to offline case itself.

2023-10-12 21:56 UTC, Johnny-kung commented
Confirmed with Jack that it's a bug related to content edit feature, not specific in this sample.

2023-10-13 02:15 UTC, mparizeau-pdftron approved these changes

2023-10-13 02:16 UTC, merged